const path = require('path');

const config = {
    'adlist': 'https://gist.githubusercontent.com/iyee/2e27c124af2f7a4f0d5a/raw/7758f00988cb817b9d5d589e548d804fa61adc51/main.conf',
    'gfwlist': 'https://raw.githubusercontent.com/R0uter/ss.conf-for-surge/master/list/gfwlist.txt',

    'template': path.join(__dirname, '..', 'template.conf'),
    'output_dir': path.join(__dirname, '..', 'conf/'),

    // your ss info here
    servers: [
        {
            "server":"ru-88.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"ru-88"
        },
        {
            "server":"ru-21.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"ru-21"
        },
        {
            "server":"cn6t.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"cn6t"
        },
        {
            "server":"cn5t.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"cn5t"
        },
        {
            "server":"cn4t.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"cn4t"
        },
        {
            "server":"cn1t.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"cn1t"
        },
        {
            "server":"cn3t.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"cn3t"
        },
        {
            "server":"cn2t.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"cn2t"
        },
        {
            "server":"hk-222.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-222"
        },
        {
            "server":"hk-172.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-172"
        },
        {
            "server":"hk-66.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-66"
        },
        {
            "server":"hk-209.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-209"
        },
        {
            "server":"hk-965.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-965"
        },
        {
            "server":"hk-252.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-252"
        },
        {
            "server":"hk-197.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-197"
        },
        {
            "server":"hk-145.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-145"
        },
        {
            "server":"hk-207.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-207"
        },
        {
            "server":"hk-52.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"hk-52"
        },
        {
            "server":"sg-60.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"sg-60"
        },
        {
            "server":"sg-189.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"sg-189"
        },
        {
            "server":"sg-150.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"sg-150"
        },
        {
            "server":"sg-16.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"sg-16"
        },
        {
            "server":"sg-54.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"sg-54"
        },
        {
            "server":"sg-187.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"sg-187"
        },
        {
            "server":"jp-111.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"jp-111"
        },
        {
            "server":"jp-739.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"jp-739"
        },
        {
            "server":"jp-177.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"jp-177"
        },
        {
            "server":"jp-162.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"jp-162"
        },
        {
            "server":"jp-109.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"jp-109"
        },
        {
            "server":"jp-59.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"jp-59"
        },
        {
            "server":"jp-210.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"jp-210"
        },
        {
            "server":"jp-107.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"jp-107"
        },
        {
            "server":"kr-180.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"kr-180"
        },
        {
            "server":"kr-215.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"kr-215"
        },
        {
            "server":"kr-216.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"kr-216"
        },
        {
            "server":"tw-36.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"tw-36"
        },
        {
            "server":"tw-22.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"tw-22"
        },
        {
            "server":"tw-216.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"tw-216"
        },
        {
            "server":"us-7137.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"us-7137"
        },
        {
            "server":"us-176.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"us-176"
        },
        {
            "server":"us-4126.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"us-4126"
        },
        {
            "server":"us-63.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"us-63"
        },
        {
            "server":"us-40.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"us-40"
        },
        {
            "server":"us-522.hxg.cc",
            "server_port":"20765",
            "local_port":"1080",
            "password":"Pw2x2eG3o0",
            "method":"rc4-md5",
            "remarks":"us-522"
        }
    ]
};

export {config};
